### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by ashim888** [hlfshell/node-packer#4]
i keep getting [Error: stdout maxBuffer exceeded], i'm trying to build an image on digitalocean but i keep getting `Fiddlesticks! Something went wrong :-( { [Error: stdout maxBuffer exceeded]
  cmd: '/bin/sh -c packer build -machine-readable /Users/ashim/Documents/timepass/ansitest/packer_info/core_template.json ' }`

my code is here
```var PackerFile = require('node-packer').PackerFile
function core_image(){
  var newImage= new PackerFile()
  newImage.filePath='path/to/my/template/packer_template.json'
  newImage.addDigitalOcean('XXX')
    .build(function(err, output){
      if(err) {
        console.error('Fiddlesticks! Something went wrong :-(', err)
      } else {
        console.log('The formatted output from the build:', output)
      }
  })
}

core_image()

**Comment by hlfshell** [comment]
I increased the max buffer size fivefold to 1 meg here:
https://github.com/hlfshell/node-packer/commit/1ed0f6c67da8ca328c69b894f1f4234ed6aca7fa

If you still have issues, try raising that maxBuffer option.

This is now in v 0.1.7, which is published.

Thank you.
