### ISSUE TITLE
JSON FORMAT

### ISSUE THREAD

**Issue by ashim888** [hlfshell/node-packer#5]
What i got in return while creating a snapshot on digitalocean is this
`[
  {
    'builder-id': 'pearkes.digitalocean',
    id: 'nyc3:21024226',
    image: '21024226',
    region: 'nyc3',
    string: 'A snapshot was created: \'xxx-nyc3-1479639236\' (ID: 21024016) in region \'nyc3\'',
    'files-count': '0'
  }
]
`
Isn't that JSON format would be
```[
  {
    "builder-id": "pearkes.digitalocean",
    "id": "nyc3:21024916",
    "image": "21024916",
    "region": "nyc3",
    "string": "A snapshot was created: \"xxx-nyc3-1479639236\" (ID: 21024016) in region \"nyc3\"",
    "files-count": "0"
  }
]

**Comment by hlfshell** [comment]
I'm not sure what you're pointing out would be different. The fact that it's in an array? (You can fire multiple builders, so the return is always in an array) The quotes around the attributes? The spacing?

**Comment by ashim888** [comment]
@hlfshell got it with `out.digitalocean.artifacts[0].image`
